In [4]:
import array
import numpy as np

In [3]:
l = list(range(10))
A = array.array('i',l)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating array from python list

In [5]:
np.array([1, 4, 2, 3, 5])

array([1, 4, 2, 3, 5])

In [6]:
#Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, 
#NumPy will upcast if possible (here, integers are upcast to floating point):
np.array([3.14, 4, 5, 7, 4])

array([3.14, 4.  , 5.  , 7.  , 4.  ])

In [7]:
np.array([1, 2, 6, 8], dtype ='float32')

array([1., 2., 6., 8.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#Creating Arrays from Scratch 

In [12]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Create a length-10 integer array filled with zeros
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Create a 3x5 array filled with 3.14 
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [27]:
# Create an array filled with a linear sequence        
# Starting at 0, ending at 20, stepping by 2        
# (this is similar to the built-in range() function) 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
# Create an array of five values evenly spaced between 0 and 1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
# Create a 3x3 array of uniformly distributed        
# random values between 0 and 1 
np.random.random((3, 3))

array([[0.73015543, 0.51837477, 0.8080285 ],
       [0.84130558, 0.6171277 , 0.99935076],
       [0.62871023, 0.58642877, 0.23260473]])

In [22]:
# Create a 3x3 array of normally distributed random values        
# with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3,3))

array([[ 0.12809333,  0.39134821,  0.50376896],
       [-0.16862509, -0.29964691, -0.50870608],
       [ 0.91887445, -0.80311483, -0.30138388]])

In [34]:
# Create a 3x3 array of random integers in the interval [0, 10) 
np.random.randint(0,10, (3,3))

array([[9, 8, 1],
       [0, 4, 3],
       [7, 7, 1]])

In [41]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# Create an uninitialized array of three integers        
# The values will be whatever happens to already exist at that        
# memory location 
np.empty(8)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.12641401e-321, 2.12199579e-314, 2.22561778e-222])